<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0BVlwqN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0BVlwqN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0BVlwqN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0BVlwqN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0BVlwqN\App_KernelDevDebugContainer([
    'container.build_hash' => '0BVlwqN',
    'container.build_id' => '2f075d77',
    'container.build_time' => 1663908702,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0BVlwqN');
